### ISSUE TITLE
Missing figure when running Hanon

### ISSUE THREAD

**Issue by irisyupingren** [omelkonian/hs-pattrans#5]
This command 
`stack exec -- hs-pattrans -h`
gives the following output in the terminal:

Starting analysis
Parsing docs/out/hanon/ref...
Parsing hanon in Parser.hs
Parsed.
hanon:exp:pattern1
hanon:exp:pattern2
hanon:exp:pattern3
hanon:exp:pattern4
hanon:exp:pattern5
hanon:exp:pattern6
ALL { 
	total: 8
	exact: 0.00% (0)
	transposed: 0.00% (0)
	tonT: 37.50% (3)
	inverted: 12.50% (1)
	augmented: 0.00% (0)
	retrograded: 0.00% (0)
	rotated: 12.50% (1)
	trI: 0.00% (0)
	trA: 0.00% (0)
	trR: 0.00% (0)
	tonrotated: 0.00% (0)
	trtonA: 0.00% (0)
	other: 37.50% (3)
}

There are six patterns in total in the dataset, which is correct. 

But when we go into ./docs/out/hanon/ref/hanon/exp/
We only see five figures generated.

**Comment by omelkonian** [comment]
Turns out this is not a real issue. 
If you check out the `flexiChecker` branch, you would see that the critical line of code that renders charts is commented out. Hence, you were probably viewing obsolete charts from a previous run.

So, uncommenting that and importing `Analysis` instead of `CompoAnalysis` does the job:
```haskell
-- import CompoAnalysis
-- import ProtoAnalysis
-- import NewAnalysis
import Analysis
...
runAnalysis :: (Bool, Bool) -> FilePath -> IO [PatternGroup] -> IO ()
...
          renderOne pg an -- produce pie chart
...
```
